#!/usr/bin/env python3
"""Gera o `THIRD-PARTY-NOTICES.txt`: as licenças de tudo o que os binários do Zeebx levam dentro.

MIT, BSD, Apache, Zlib, OFL e a LGPL do Qt pedem que o aviso de copyright e o texto da licença
acompanhem o binário. O arquivo é versionado e vai em todos os pacotes da release; o
`release.yml` roda este script com `--confere` e para se ele estiver velho.

Três partes, porque o `cargo about` só enxerga crates:

- as crates, pelo `cargo about` com o `about.toml` da raiz;
- o C++ que o `dynarmic` compila junto (fmt, mcl, xbyak, zydis…), lido da cópia da crate no
  registro do cargo;
- o Qt 6, que vai dentro do AppImage, do instalador do Windows e do `.dmg` do frontend Qt.

    python3 ferramentas/avisos_de_terceiros.py            # reescreve o arquivo
    python3 ferramentas/avisos_de_terceiros.py --confere  # só diz se está em dia

Precisa do `cargo about` na versão abaixo (`cargo install --locked cargo-about --features cli
--version ...`): outra versão formata diferente, e o `--confere` acusaria diferença que não é.
"""

import json
import pathlib
import subprocess
import sys

VERSAO_DO_CARGO_ABOUT = "0.9.2"

RAIZ = pathlib.Path(__file__).resolve().parent.parent
SAIDA = RAIZ / "THIRD-PARTY-NOTICES.txt"
LICENCAS = RAIZ / "ferramentas" / "licencas"

# Os `externals` do dynarmic que entram no binário. Ficam de fora o `catch`, que é só dos testes
# dele, e o `biscuit`, que só é compilado quando o host é RISC-V.
EXTERNOS_DO_DYNARMIC = [
    ("fmt", "externals/fmt/LICENSE"),
    ("mcl", "externals/mcl/LICENSE"),
    ("oaknut", "externals/oaknut/LICENSE"),
    ("robin-map", "externals/robin-map/LICENSE"),
    ("xbyak", "externals/xbyak/COPYRIGHT"),
    ("zydis", "externals/zydis/LICENSE"),
    ("zycore", "externals/zydis/dependencies/zycore/LICENSE"),
    ("Boost (headers)", "externals/ext-boost/LICENSE_1_0.txt"),
]

CABECALHO = """\
Third-party software in Zeebx
=============================

The Zeebx source code is GPL-2.0-or-later (see LICENSE). The binaries are distributed under the
GPLv3 (see LICENSE-GPL3), because they link Apache-2.0 libraries listed below.

This file lists the licenses of the third-party software included in those binaries. It is
generated by ferramentas/avisos_de_terceiros.py; do not edit it by hand.
"""

QT = """\
================================================================================
Qt 6 (LGPL-3.0-only)

Used by: the Qt frontend (zeebx-qt). The AppImage, the Windows installer and the macOS .dmg ship
the Qt libraries QtCore, QtGui, QtQml and QtQuick, dynamically linked; the .deb uses the Qt from
the system. You may replace them with your own build of Qt.

Qt is Copyright (C) The Qt Company Ltd. and other contributors.
Source code: https://download.qt.io/official_releases/qt/
The LGPLv3 builds on the GPLv3, whose text is in LICENSE-GPL3.
--------------------------------------------------------------------------------

"""


def roda(*comando: str) -> str:
    return subprocess.run(comando, cwd=RAIZ, check=True, capture_output=True, text=True).stdout


def confere_versao() -> None:
    versao = roda("cargo", "about", "--version").split()[-1]
    if versao != VERSAO_DO_CARGO_ABOUT:
        sys.exit(f"cargo about {versao}, e o arquivo é gerado com a {VERSAO_DO_CARGO_ABOUT}")


def crates() -> str:
    return roda(
        "cargo", "about", "generate", "--workspace", "--all-features", "--locked",
        "-c", "about.toml", str(LICENCAS / "about.hbs"),
    )


def dynarmic() -> str:
    metadados = json.loads(roda("cargo", "metadata", "--format-version", "1", "--locked"))
    pacote = next(p for p in metadados["packages"] if p["name"] == "dynarmic")
    raiz = pathlib.Path(pacote["manifest_path"]).parent / "dynarmic"
    partes = []
    for nome, caminho in [("dynarmic", "LICENSE.txt")] + EXTERNOS_DO_DYNARMIC:
        texto = (raiz / caminho).read_text(encoding="utf-8").strip()
        partes.append(
            "=" * 80 + f"\n{nome} (C++, built into the dynarmic crate)\n" + "-" * 80
            + f"\n\n{texto}\n\n"
        )
    return "".join(partes)


def gera() -> str:
    lgpl = (LICENCAS / "LGPL-3.0.txt").read_text(encoding="utf-8")
    return CABECALHO + crates() + dynarmic() + QT + lgpl


def main() -> None:
    confere_versao()
    texto = gera()
    if "--confere" in sys.argv[1:]:
        if not SAIDA.exists() or SAIDA.read_text(encoding="utf-8") != texto:
            sys.exit(
                "THIRD-PARTY-NOTICES.txt está velho: rode python3 ferramentas/avisos_de_terceiros.py"
            )
        print("THIRD-PARTY-NOTICES.txt em dia")
        return
    SAIDA.write_text(texto, encoding="utf-8")
    print(f"{SAIDA.name}: {len(texto) // 1024} KiB")


if __name__ == "__main__":
    main()
